[project]

name        = "basic-hll"
version     = "0.0.1"
authors     = ["kjgorman <kieran@kjgorman.com>"]
description = "The basic HyperLogLog algorithm"
homepage    = "https://github.com/kjgorman/hll.rs"
repository  = "https://github.com/kjgorman/hll.rs"
license     = "MIT"
keywords    = ["hyperloglog", "hll"]

[lib]
name = "basic-hll"
path = "src/lib.rs"